version: "3"
services:
  web:
    build: .
    image: sexyferretpleroma
    container_name: pleroma_web
    restart: always
    ports:
      - '127.0.0.1:4000:4000'
    volumes:
      - ./uploads:/pleroma/uploads
